---
title: "EAPSI UM Timing Files"
author: "Steven R. Anderson"
output: html_notebook
---


```{r}
rm(list=ls()) #removes all the variables from workspace

library(dplyr)

#formula to select run_number
substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}
```


#Import log

```{r load data, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE}
original<- read.csv("//datastore01.psy.miami.edu/Groups/ELosin_Lab/Research/Research_Projects/EAPSI_Miami/Data_Files/Presentation_logfiles_CSV/0031-EAPSI_Scan_Task2_7_11_18_EN_Run3.csv")

master<-original

```

#Select initial time (=fmri_trigger)
```{r}
master<-master[-1,]

#define start_time using time of the first 5 button press after screen trigger_wait
# #first relevant 5 button press is always immediately after "trigger_wait"
#   i<-as.numeric(match('trigger_wait',master$Code))
#   start_time<-as.numeric(master[i+1, c("Time")])
#   message(start_time)
#   dtrRow<-as.numeric(match('discarded_TRs',master$Code)) #find start of discarded TRs
#   bslRow<-as.numeric(match('baseline',master$Code)) #find start of baseline
#   discarded_TR_duration<- as.numeric(master[bslRow,c("Time")]) - as.numeric(master[dtrRow,c("Time")])
#   #discarded_TR_duration<-130000
#   message(discarded_TR_duration)

bslRow<-as.numeric(match('baseline',master$Code)) #find start of baseline
baseline_time<-as.numeric(master[bslRow,c("Time")])
#baseline_time<-baseline_time-65000 #subtract 6.5s because that is what the discarded TR duration should have been, as it's TR=1.3x5=6.5

#Get Run Number
run<-filter(master, grepl("run_",Code))
run<- as.character(run$Code[1])
run<-as.numeric(substrRight(run, 1))
#run<-paste0("0", run)


#Select Subject number
subject<- as.numeric(master[1,c("Subject")])
#subject<-str_pad(subject, 4, pad = "0")

```

#Remove rows not needed (e.g. response lines, bp_lines)
```{r}
#Empty rows
master<-master[which(master$letter.str. != ''),]

#rows with answers
#remove all the rows with biopac or response in Code
master<-filter(master, !grepl("bp",Code))

```

#Subtract (time - initial time) and divide by 10,000 to get initial time
```{r}
for (i in 1:nrow(master)){
  master[i, c("Time_sec")] <- ((master[i,c("Time")]) - baseline_time)/10000
}

```

#Get duration: (cell n+1 - Cell n)
```{r}
for (i in 1:nrow(master)){
  master[i, c("Duration_sec")]<- (master[(i+1), c("Time_sec")] -master[(i), c("Time_sec")])
}
  
```

#Timing Image Check
```{r}
  #Create new column for time in seconds
  #Subtract ((time - initial time) -100000) and divide by 10,000 to get initial time
  #100000 accounts for the first 10 TRs that are thrown away by GE
#  for (i in 1:nrow(image)){
#    image[i, c("Time_sec")]<- ((image[i, c("Time")] - start_time)-baseline_time)/10000
#  }

  #Create new column for Duration in seconds
  #Get duration: (cell n+1 - Cell n)
#  for (i in 1:nrow(image)){
#    image[i, c("Duration_sec")]<- (image[(i+1), c("Time_sec")] -image[(i), c("Time_sec")])
#  }

  #create variables with only image information
#  temp<-data.frame(matrix(nrow=2, ncol=3))
#  for (i in 1:nrow(image)){ 
##    temp[i,1]<- as.character(image[i, c("Code")])
 #   temp[i,2]<- image[i, c("Time_sec")]
 #   temp[i,3]<- image[i, c("Duration_sec")]
 # }
 #   image_check<-temp
```

#loop through each element and parse
```{r}
names<- c("baseline","end_run")
stim_list<-c()

for (k in 1:length(names)){
  temp<-data.frame(matrix(nrow=2, ncol=4))
  x<-(names[k]) 
  #print(paste(x))
  for (i in 1:nrow(master)){
    if  (master[i, c("Code")] == x ){
      temp[i,1]<- as.character(master[i, c("Code")])
      temp[i,2]<- master[i, c("Time_sec")]
      temp[i,3]<- master[i, c("Duration_sec")]
      temp[i,4]<-1
    }
    temp = temp %>% na.omit() #remove empty rows
    new_temp<- temp[,2:4]
    assign(paste(x),new_temp) #creates new data frame with for specific variable
  }
  stim_list<- c(stim_list, (paste(x)))
  }
```


```{r}
names_fix<- c("fix", "catchup")


for (k in 1:length(names_fix)){
 temp<-data.frame(matrix(nrow=2, ncol=4))
  x<-(names_fix[k]) 
  #print(paste(x))
  for (i in 1:nrow(master)){
    if  (master[i, c("Code")] == x ){
      temp[i,1]<- as.character(master[i, c("Code")])
      temp[i,2]<- master[i, c("Time_sec")]
      temp[i,3]<- master[i, c("Duration_sec")]
      temp[i,4]<-1
    }
    temp = temp %>% na.omit() #remove empty rows
    #fix<-temp
    #new_temp<- temp[,2:4]
    assign(paste(x),temp) #creates new data frame with for specific variable
  }
}

#creates 
fixation<-rbind(fix,catchup)
fixation[,1]<-NULL
stim_list<- c(stim_list, "fixation")

rm(fix, catchup)
```

```{r}
#cue by level
levels<- c("_lookneu_", "_lookneg_", "_suppress_" )
names<- c("cue")
    
for (a in 1:length(levels)){
  temp_level<- (levels[a])
  level_df<- filter(master, grepl(temp_level,Code))
  level_name<-gsub(".$", "", temp_level) 
  for (k in 1:length(names)){
    temp<-data.frame(matrix(nrow=2, ncol=4))
    cue_type<-(names[k])
    #print(paste(stim_type, temp_level))
    for (i in 1:nrow(level_df)){
      if (grepl(cue_type, level_df[i,c("Code")])==TRUE){
        temp[i,1]<- as.character(level_df[i, c("Code")])
        temp[i,2]<- level_df[i, c("Time_sec")]
        temp[i,3]<- level_df[i, c("Duration_sec")]
        temp[i,4]<-1
      }
      temp = temp %>% na.omit() #remove empty rows
      new_temp<- temp[,2:4]
      assign(paste(cue_type,level_name,sep=""),new_temp)
      
    }
    stim_list<- c(stim_list, (paste(cue_type,level_name,sep="")))
  }
}

```


```{r}
#stim by level
levels<- c("_lookneu_", "_lookneg_", "_suppress_" )
names<- c("stim")
    
for (a in 1:length(levels)){
  temp_level<- (levels[a])
  level_df<- filter(master, grepl(temp_level,Code))
  level_name<-gsub(".$", "", temp_level) 
  for (k in 1:length(names)){
    temp<-data.frame(matrix(nrow=2, ncol=4))
    stim_type<-(names[k])
    #print(paste(stim_type, temp_level))
    for (i in 1:nrow(level_df)){
      if (grepl(stim_type, level_df[i,c("Code")])==TRUE){
        temp[i,1]<- as.character(level_df[i, c("Code")])
        temp[i,2]<- level_df[i, c("Time_sec")]
        temp[i,3]<- level_df[i, c("Duration_sec")]
        temp[i,4]<-1
      }
      temp = temp %>% na.omit() #remove empty rows
      new_temp<- temp[,2:4]
      assign(paste(stim_type,level_name,sep=""),new_temp)
      
    }
    stim_list<- c(stim_list, (paste(stim_type,level_name,sep="")))
  }
}

```

```{r}
#create late and early onset suppression stim files to model potential late onset suppression effects
#stim_suppressearly_duration<-(stim_suppress$X3)/2
#stim_suppressearly<-cbind.data.frame(stim_suppress$X2,stim_suppressearly_duration,stim_suppress$X4)
#colnames(stim_suppressearly)<-c("X2","X3","X4")

#stim_suppresslate_onset<-(stim_suppress$X2)+3.5122
#stim_suppresslate_duration<-(stim_suppress$X3)/2
#stim_suppresslate<-cbind.data.frame(stim_suppresslate_onset,stim_suppresslate_duration,stim_suppress$X4)
#colnames(stim_suppresslate)<-c("X2","X3","X4")

#add to stim list
#stim_list<- c(stim_list, "stim_suppressearly","stim_suppresslate")

```

```{r}
  #Saving all data files using loop
    
    #Setting up Directory names
    mainDir <- "//datastore01.psy.miami.edu/Groups/ELosin_Lab/Research/Research_Projects/EAPSI_Miami/Data_Files/Timing_Files"
    subDir <- paste("sub-", (subject), sep="")
    
    #Creating folder for specific subject
    if (file.exists(subDir)){
      setwd(file.path(mainDir, subDir))
    } else {
      dir.create(file.path(mainDir, subDir), showWarnings = FALSE)
      setwd(file.path(mainDir, subDir))
    }
    
    #saving
    for (i in 1:length(stim_list)){
      write.table(get(stim_list[i]), paste(mainDir, "/",subDir,"/", "sub-",(subject), "_","task-02","_", "run-0",(run),"_",(stim_list)[i], "_","events",".tsv", sep = ""), col.names = FALSE, row.names = FALSE, sep = "\t", quote = FALSE)
    } 

    
```



