---
title: "Violin Plots with Subject Lines"
author: "Steven Anderson"
date: "January 13, 2020"
output:
  html_document:
toc: true
toc_float: true
smooth_scroll: true
theme: united
highlight: tango
---

###Setup
```{r Setup, results="hide",warning=FALSE, message=FALSE}
library(reshape2)
library(ggstatsplot)
library(ggplot2)
library(corrplot)
library(psych)
library(ggpubr) 
```

##Prepare data
```{r Test if PINES response differs by condition, results="hide",warning=FALSE, message=FALSE}
#read in PINES values from task1 cope6 (LNEU>Baseline) and cope7 (LNEG>Baseline) 
pines_values_task1_cope6_cope7 <- read.csv(file="//datastore01.psy.miami.edu/Groups/ELosin_Lab/Research/Research_Projects/EAPSI_Beijing/Data_Files/vps-pines/output/PINES_task1_cope6_cope7.csv", header=T, sep=",")

#create subject variable
pines_values_task1_cope6_cope7$Subject<-seq(1,30)

#make Subject factor
pines_values_task1_cope6_cope7$Subject<-as.factor(pines_values_task1_cope6_cope7$Subject)

#rename columns
colnames(pines_values_task1_cope6_cope7)<-c("LNEU","LNEG","Subject")

#melt
pines_values_task1_cope6_cope7_melted<-melt(pines_values_task1_cope6_cope7,id="Subject")

```

##Plot with ggplot and subject lines 
```{r Plot with ggplot and subject lines , warning=FALSE, message=FALSE}
r <- ggplot(pines_values_task1_cope6_cope7_melted, aes(variable, value,(colour=variable)),alpha=.06) + guides(fill=FALSE) 
f <- r + geom_violin(aes(colour=variable),trim=F,width = 0.6,size=1.2) 
j <- f + geom_point(data=pines_values_task1_cope6_cope7_melted,aes(colour=variable),size=3)+ stat_summary(aes(group=variable),geom = "point", fun.y = mean, shape = 18, size = 5,col="gray21",position = position_dodge(width=.48)) + geom_line(aes(group = Subject),col="gray48",alpha=.3) + geom_hline(yintercept=0, linetype="dashed", color = "gray34") 
d <- j+theme_classic() + theme(legend.position = "none") + ylab("PINES Response") + xlab("") + scale_colour_manual(values = c("dodgerblue3", "tan2"))

#add facet grid and signficance labels
pines_values_task1_cope6_cope7_plot <- d  + stat_compare_means(label = "p.signif",paired=TRUE,method="t.test", label.x = 1.4,size=8,label.y=15)

pines_values_task1_cope6_cope7_plot

```

##Plot with ggstatsplot with subject lines
```{r Plot with ggstatsplot, warning=FALSE, message=FALSE}
#make cope numeric (if getting error in ggwithinstats)
pines_values_task1_cope6_cope7_melted$variable2 <- as.numeric(pines_values_task1_cope6_cope7_melted$variable)

#plot
ggstatsplot::ggwithinstats(
  data = pines_values_task1_cope6_cope7_melted,
  x = variable2,
  y = value,
  ylab = "PINES Response",
  xlab = "Face Task Condition",
  outlier.tagging = F,
  ggstatsplot.layer = FALSE,
  messages = T,ggtheme = ggplot2::theme_bw(),results.subtitle = T)
```

##Plot with ggplot and no subject lines
```{r Plot with ggplot and no subject lines, warning=FALSE, message=FALSE}
r <- ggplot(pines_values_task1_cope6_cope7_melted, aes(variable, value,(colour=variable)),alpha=.06) + guides(fill=FALSE) 
f <- r + geom_violin(aes(colour=variable),trim=F,width = 0.6,size=1.2) 
j <- f + geom_point(data=pines_values_task1_cope6_cope7_melted,aes(colour=variable),size=3)+ stat_summary(aes(group=variable),geom = "point", fun.y = mean, shape = 18, size = 5,col="gray21",position = position_dodge(width=.48)) 
d <- j+theme_classic() + theme(legend.position = "none") + ylab("PINES Response") + xlab("") + scale_colour_manual(values = c("dodgerblue3", "tan2"))

#add facet grid and signficance labels
pines_values_task1_cope6_cope7_plot <- d  + stat_compare_means(label = "p.signif",paired=TRUE,method="t.test", label.x = 1.4,size=8,label.y=15)

pines_values_task1_cope6_cope7_plot
```
